"use client";

import { useEffect, useMemo, useState } from "react";

type Book = { id:string; title:string; author:string; genre:string; mood:string; description:string; pages:number; color:string; content?:string[] };
type Shelf = "queue" | "reading" | "read";
type Saved = { bookId:string; shelf:Shelf; progress:number };
const books: Book[] = [
  {id:"alchemist",title:"The Alchemist",author:"Paulo Coelho",genre:"Fiction",mood:"hopeful",description:"A luminous fable about purpose, courage and following your own path.",pages:208,color:"#c4824d"},
  {id:"secret-garden",title:"The Secret Garden",author:"Frances Hodgson Burnett",genre:"Classics",mood:"uplifting",description:"A restorative public-domain story about friendship, curiosity and renewal.",pages:180,color:"#739a72",content:["Mary Lennox was sent to Misselthwaite Manor to live with her uncle. At first she found the wide house lonely, but a robin led her towards a door hidden by ivy.","The key had been buried for ten years. When Mary turned it, the secret garden breathed again: roses, earth and the possibility of beginning anew.","Every morning the garden changed a little, and so did Mary. She learned that tending a living thing is one of the gentlest ways to tend oneself."]},
  {id:"little-prince",title:"The Little Prince",author:"Antoine de Saint-Exupéry",genre:"Fiction",mood:"gentle",description:"A tender, imaginative reflection on attention, friendship and what matters.",pages:96,color:"#7697bd"},
  {id:"walden",title:"Walden",author:"Henry David Thoreau",genre:"Nature",mood:"thoughtful",description:"A public-domain meditation on simple living, nature and deliberate days.",pages:224,color:"#788b71",content:["I went to the woods because I wished to live deliberately, to front only the essential facts of life.","Morning brings back the heroic ages. The smallest sound becomes an invitation to notice the world anew.","Simplify, simplify. Make room for the things that give a day its true shape."]},
  {id:"frankenstein",title:"Frankenstein",author:"Mary Shelley",genre:"Classics",mood:"immersive",description:"A public-domain gothic classic about ambition, responsibility and belonging.",pages:280,color:"#715a7c",content:["I had worked hard for nearly two years, for the sole purpose of infusing life into an inanimate body.","Learn from me, if not by my precepts, at least by my example, how dangerous is the acquirement of knowledge.","Nothing is so painful to the human mind as a great and sudden change."]},
  {id:"anne",title:"Anne of Green Gables",author:"L. M. Montgomery",genre:"Classics",mood:"joyful",description:"A public-domain coming-of-age classic full of imagination and warmth.",pages:320,color:"#cc857f",content:["It is delightful when your imaginations come true, isn't it?", "Anne had a way of finding wonder in ordinary places and making room for it in every conversation.","Tomorrow is always fresh, with no mistakes in it yet."]}
];
const quotes=["A book is a quiet place to become more yourself.","Read slowly enough for an idea to stay.","The right book is often a small act of kindness."];

export default function Home() {
 const [mounted,setMounted]=useState(false), [user,setUser]=useState<string|null>(null), [view,setView]=useState("home"), [dark,setDark]=useState(false), [onStep,setOnStep]=useState(1), [genres,setGenres]=useState<string[]>(["Fiction","Classics"]), [mood,setMood]=useState("I want something hopeful, short, and easy."), [batch,setBatch]=useState(0), [saved,setSaved]=useState<Saved[]>([{bookId:"secret-garden",shelf:"reading",progress:34}]), [reader,setReader]=useState<Book|null>(null), [page,setPage]=useState(0), [highlight,setHighlight]=useState(""), [quotesSaved,setQuotesSaved]=useState<string[]>([]), [bookmarked,setBookmarked]=useState(false), [comments,setComments]=useState(["The Secret Garden feels exactly right for a slow weekend.","I am joining the July reading challenge — 20 minutes a day."]), [comment,setComment]=useState("");
 useEffect(()=>{const raw=localStorage.getItem("booktender-demo");if(raw){try{const d=JSON.parse(raw);setUser(d.user);setSaved(d.saved||[]);setQuotesSaved(d.quotes||[])}catch{}}setMounted(true)},[]);
 useEffect(()=>{if(mounted) localStorage.setItem("booktender-demo",JSON.stringify({user,saved,quotes:quotesSaved}))},[mounted,user,saved,quotesSaved]);
 const recs=useMemo(()=>{const pools=[[books[0],books[1],books[2]],[books[3],books[4],books[5]]];return pools[batch%2]},[batch]);
 const save=(id:string,shelf:Shelf="queue")=>setSaved(s=>s.some(x=>x.bookId===id)?s.map(x=>x.bookId===id?{...x,shelf}:x):[...s,{bookId:id,shelf,progress:0}]);
 const open=(book:Book)=>{if(!book.content){setReader(books[1])}else setReader(book);setPage(0);setView("reader")};
 const nav=(to:string)=>{setReader(null);setView(to)};
 if(!mounted) return null;
 if(!user) return <div className={dark?"dark":""}><main className="app"><Auth onDemo={(name)=>{setUser(name);setView("onboarding")}} dark={dark} setDark={setDark}/></main></div>;
 if(view==="onboarding") return <div className={dark?"dark":""}><main className="app"><Header view={view} nav={nav} dark={dark} setDark={setDark}/><Onboarding step={onStep} setStep={setOnStep} genres={genres} setGenres={setGenres} finish={()=>nav("home")}/></main></div>;
 return <div className={dark?"dark":""}><main className="app"><Header view={view} nav={nav} dark={dark} setDark={setDark}/>{reader?<Reader book={reader} page={page} setPage={setPage} highlight={highlight} setHighlight={setHighlight} saveQuote={()=>highlight&&setQuotesSaved(q=>[...q,highlight])} bookmarked={bookmarked} setBookmarked={setBookmarked} complete={()=>{save(reader.id,"read");setReader(null);nav("library")}}/>:<>{view==="home"&&<Discover user={user} mood={mood} setMood={setMood} recs={recs} batch={batch} setBatch={setBatch} save={save} saved={saved} open={open}/>} {view==="library"&&<Library saved={saved} save={save} open={open}/>} {view==="community"&&<Community comments={comments} comment={comment} setComment={setComment} add={()=>{if(comment.trim()){setComments(c=>[comment,...c]);setComment("")}}}/>} {view==="profile"&&<Profile user={user} genres={genres} quotes={quotesSaved}/>} {view==="admin"&&<Admin/>}</>}<MobileNav view={view} nav={nav}/></main></div>;
}
function Header({view,nav,dark,setDark}:{view:string;nav:(x:string)=>void;dark:boolean;setDark:(x:boolean)=>void}){return <header className="shell nav"><button className="brand" onClick={()=>nav("home")}><span className="mark">✦</span>Booktender</button><nav className="navlinks">{[["home","Discover"],["library","My Library"],["community","Community"],["profile","Profile"],["admin","Admin"]].map(([id,label])=><button className={view===id?"active":""} key={id} onClick={()=>nav(id)}>{label}</button>)}</nav><div className="nav-actions"><button className="iconbtn" aria-label="Toggle colour mode" onClick={()=>setDark(!dark)}>{dark?"☀":"◐"}</button><span className="chip">Demo reader</span></div></header>}
function Auth({onDemo,dark,setDark}:{onDemo:(n:string)=>void;dark:boolean;setDark:(x:boolean)=>void}){return <><header className="shell nav"><div className="brand"><span className="mark">✦</span>Booktender</div><button className="iconbtn" onClick={()=>setDark(!dark)}>{dark?"☀":"◐"}</button></header><section className="auth card"><span className="eyebrow">Read with intention</span><h1>Find a book.<br/>Actually read it.</h1><p style={{color:"var(--muted)",lineHeight:1.6}}>Your calm, personal reading companion — from discovery to the last page.</p><div className="demo-grid">{["Demo Reader 1 — thoughtful fiction","Demo Reader 2 — classics and slow reads","Demo Reader 3 — short hopeful books"].map((x,i)=><button key={x} className="demo" onClick={()=>onDemo(`Demo Reader ${i+1}`)}><b>{x.split(" — ")[0]}</b><span>{x.split(" — ")[1]} · one-click demo access</span></button>)}</div><div className="row" style={{marginTop:20}}><button className="btn btn-primary" onClick={()=>onDemo("New Reader")}>Create a demo account</button><span style={{fontSize:12,color:"var(--muted)"}}>No real data required for this demo.</span></div></section></>}
function Onboarding({step,setStep,genres,setGenres,finish}:{step:number;setStep:(x:number)=>void;genres:string[];setGenres:(x:string[])=>void;finish:()=>void}){const toggle=(g:string)=>setGenres(genres.includes(g)?genres.filter(x=>x!==g):[...genres,g]);return <section className="auth card"><span className="eyebrow">A few small questions</span><div className="stepper">{[1,2,3].map(x=><i className={x<=step?"on":""} key={x}/>)}</div>{step===1&&<><h1>What do you reach for?</h1><p style={{color:"var(--muted)"}}>Choose the genres that feel like home. You can edit this later.</p><div className="chips">{["Fiction","Classics","Nature","Mystery","History","Poetry"].map(g=><button className={`chip ${genres.includes(g)?"selected":""}`} key={g} onClick={()=>toggle(g)}>{g}</button>)}</div></>}{step===2&&<><h1>Three books you loved.</h1><p style={{color:"var(--muted)"}}>These help Booktender understand your taste.</p><div className="chips">{books.slice(0,5).map(b=><span className="chip selected" key={b.id}>{b.title}</span>)}</div></>}{step===3&&<><h1>Make room to read.</h1><p style={{color:"var(--muted)"}}>We’ll start you with short, gentle recommendations and a living reading shelf.</p><div className="card soft" style={{padding:16,marginTop:18}}>Your first prompt is ready: “I want something hopeful, short, and easy.”</div></> }<div className="row" style={{marginTop:28}}>{step>1&&<button className="btn btn-secondary" onClick={()=>setStep(step-1)}>Back</button>}<button className="btn btn-primary" onClick={()=>step<3?setStep(step+1):finish()}>{step<3?"Continue":"Open Booktender"}</button></div></section>}
function Discover({user,mood,setMood,recs,batch,setBatch,save,saved,open}:{user:string;mood:string;setMood:(x:string)=>void;recs:Book[];batch:number;setBatch:(x:number)=>void;save:(x:string,s?:Shelf)=>void;saved:Saved[];open:(b:Book)=>void}){return <div className="shell"><section className="hero"><span className="eyebrow">Hello, {user}</span><h1>What do you need from a book today?</h1><p>Three considered choices from a real, verified catalogue — then a quiet place to begin.</p><div className="card discovery"><textarea value={mood} onChange={e=>setMood(e.target.value)} aria-label="Describe your reading mood"/><div className="chips">{["Hopeful","Short read","Gentle","Thoughtful"].map(c=><button className="chip" key={c} onClick={()=>setMood(`I want something ${c.toLowerCase()}, short, and easy.`)}>{c}</button>)}</div><button className="btn btn-primary" onClick={()=>setBatch(batch)}>Find My 3 Books</button></div></section><section className="section"><div className="section-title"><div><h2>Your three books</h2><p>Chosen for a hopeful mood, an easy pace and a little lift.</p></div><button className="btn btn-secondary btn-small" onClick={()=>setBatch(batch+1)}>Next 3 recommendations →</button></div><div className="book-grid">{recs.map((b,i)=><article className="book card" key={b.id}><div className="cover" style={{background:b.color}}>{b.title}</div><div><span className="eyebrow">{b.genre} · {b.pages} pp</span><h3>{b.title}</h3><p>{b.author}</p><div className="reason">{i===0?"A hopeful, purpose-led story that stays light on its feet.":i===1?"A restorative classic — ideal when you want warmth without pressure.":"Short, tender and quietly brilliant for a gentle reading reset."}</div><div className="row"><button className="btn btn-primary btn-small" onClick={()=>save(b.id)}>+ Reading Queue</button><button className="btn btn-secondary btn-small" onClick={()=>open(b)}>Read a sample</button></div></div></article>)}</div></section><section className="split section"><div className="spotlight card"><span className="eyebrow">Literary spotlight</span><blockquote>“{quotes[batch%quotes.length]}”</blockquote><cite>Booktender reading note · changes gently with each recommendation set</cite></div><div className="card stat"><span className="eyebrow">Continue reading</span><strong>The Secret Garden</strong><p style={{color:"var(--muted)",fontSize:14}}>34% complete · 7 min left in today’s session</p><div className="progress"><i style={{width:"34%"}}/></div></div></section></div>}
function Library({saved,save,open}:{saved:Saved[];save:(x:string,s?:Shelf)=>void;open:(b:Book)=>void}){return <section className="shell section"><div className="section-title"><div><span className="eyebrow">Your personal shelves</span><h2>My Library</h2></div></div>{(["queue","reading","read"] as Shelf[]).map(shelf=><div className="shelf card" key={shelf}><div className="section-title"><h2 style={{fontSize:23}}>{shelf==="queue"?"Reading Queue":shelf==="reading"?"Currently Reading":"Read"}</h2><p>{saved.filter(x=>x.shelf===shelf).length||"No"} book{saved.filter(x=>x.shelf===shelf).length===1?"":"s"}</p></div><div className="shelf-list">{saved.filter(x=>x.shelf===shelf).map(x=>{const b=books.find(b=>b.id===x.bookId)!;return <article className="shelf-item" key={x.bookId}><div className="cover" style={{background:b.color,width:52,height:70,fontSize:11}}>{b.title}</div><b>{b.title}</b><span style={{fontSize:12,color:"var(--muted)"}}>{x.progress}% complete</span><div className="row" style={{marginTop:10}}><button className="btn btn-secondary btn-small" onClick={()=>open(b)}>Open</button>{shelf!=="read"&&<button className="btn btn-small" style={{background:"var(--sage)"}} onClick={()=>save(b.id,shelf==="queue"?"reading":"read")}>{shelf==="queue"?"Start":"Finish"}</button>}</div></article>})}{!saved.some(x=>x.shelf===shelf)&&<p style={{color:"var(--muted)",margin:4}}>Your {shelf==="queue"?"next great read":shelf==="reading"?"current read":"finished books"} will appear here.</p>}</div></div>)}</section>}
function Reader({book,page,setPage,highlight,setHighlight,saveQuote,bookmarked,setBookmarked,complete}:{book:Book;page:number;setPage:(x:number)=>void;highlight:string;setHighlight:(x:string)=>void;saveQuote:()=>void;bookmarked:boolean;setBookmarked:(x:boolean)=>void;complete:()=>void}){const pages=book.content||books[1].content!;return <section className="reader card"><span className="eyebrow">Public-domain reading sample · {book.title}</span><div className="reader-toolbar"><span>Page {page+1} of {pages.length} · {Math.round(((page+1)/pages.length)*100)}%</span><div className="row"><button className="btn btn-secondary btn-small" onClick={()=>setBookmarked(!bookmarked)}>{bookmarked?"★ Bookmarked":"☆ Bookmark"}</button><button className="btn btn-secondary btn-small" onClick={()=>{const s=window.getSelection()?.toString().trim();if(s)setHighlight(s)}}>Highlight selection</button></div></div><p className="reader-text" onMouseUp={()=>{const s=window.getSelection()?.toString().trim();if(s)setHighlight(s)}}>{pages[page]}</p>{highlight&&<div className="card soft" style={{padding:14,margin:"22px 0"}}><b>Selected passage</b><p style={{margin:"7px 0",color:"var(--muted)"}}>{highlight}</p><button className="btn btn-primary btn-small" onClick={saveQuote}>Save as quote</button></div>}<div className="row" style={{justifyContent:"space-between",marginTop:34}}><button className="btn btn-secondary" disabled={page===0} onClick={()=>setPage(page-1)}>← Previous</button>{page<pages.length-1?<button className="btn btn-primary" onClick={()=>setPage(page+1)}>Next page →</button>:<button className="btn btn-primary" onClick={complete}>Complete session ✓</button>}</div></section>}
function Community({comments,comment,setComment,add}:{comments:string[];comment:string;setComment:(x:string)=>void;add:()=>void}){return <section className="shell section"><span className="eyebrow">One good room for readers</span><h2 className="serif" style={{fontSize:42,margin:"8px 0 20px"}}>The Sunday Shelf</h2><div className="split"><div className="card" style={{padding:20}}><span className="eyebrow">This week’s shared challenge</span><h3 className="serif" style={{fontSize:25,margin:"8px 0"}}>Read 2,000 pages together</h3><p style={{color:"var(--muted)"}}>1,356 pages logged by 42 readers. A little reading adds up.</p><div className="progress"><i style={{width:"68%"}}/></div><p style={{fontSize:13}}>68% complete · ends Sunday</p></div><div className="card" style={{padding:20}}><span className="eyebrow">Upcoming gathering</span><h3 className="serif" style={{fontSize:25,margin:"8px 0"}}>The Secret Garden discussion</h3><p style={{color:"var(--muted)"}}>Saturday, 6:30 pm · Bring one line that stayed with you.</p></div></div><div className="card" style={{padding:20,marginTop:16}}><div className="section-title"><h2 style={{fontSize:25}}>Reader notes</h2><p>Kind, spoiler-light conversation</p></div><div>{comments.map((x,i)=><p key={i} style={{borderBottom:"1px solid var(--line)",padding:"12px 0",margin:0}}><b style={{fontSize:13}}>Reader {i+1}</b><br/><span style={{color:"var(--muted)"}}>{x}</span></p>)}</div><div className="row" style={{marginTop:14}}><input aria-label="Add a community comment" value={comment} onChange={e=>setComment(e.target.value)} placeholder="Recommend a book or share a thought…" style={{flex:1,minWidth:200,border:"1px solid var(--line)",padding:11,borderRadius:11}}/><button className="btn btn-primary" onClick={add}>Post</button></div></div></section>}
function Profile({user,genres,quotes}:{user:string;genres:string[];quotes:string[]}){return <section className="shell section"><span className="eyebrow">Your reading rhythm</span><h2 className="serif" style={{fontSize:42,margin:"8px 0 20px"}}>{user}</h2><div className="stats">{[["4","Current streak"],["12","Longest streak"],["7","Reading days"],[String(quotes.length),"Saved quotes"]].map(([a,b])=><div className="stat card" key={b}><span className="eyebrow">{b}</span><strong>{a}</strong></div>)}</div><div className="card" style={{padding:20,marginTop:16}}><h3 className="serif" style={{fontSize:24,marginTop:0}}>Favourite genres</h3><div className="chips">{genres.map(x=><span className="chip selected" key={x}>{x}</span>)}</div><p style={{color:"var(--muted)"}}>Achievement unlocked: <b>Gentle starter</b> — you made room for a reading habit.</p></div></section>}
function Admin(){return <section className="shell section"><div className="card" style={{padding:28}}><span className="eyebrow">Safe demonstration</span><h2 className="serif" style={{fontSize:36,margin:"8px 0"}}>Admin preview — read only</h2><p style={{color:"var(--muted)",maxWidth:650,lineHeight:1.6}}>This public demo deliberately cannot change catalogue books, reading content, events or challenges. A real administrator is protected by Supabase role checks when the secure backend is connected.</p><div className="stats"><div className="stat soft"><span className="eyebrow">Catalogue</span><strong>6 books</strong></div><div className="stat soft"><span className="eyebrow">Community</span><strong>1 active</strong></div></div></div></section>}
function MobileNav({view,nav}:{view:string;nav:(x:string)=>void}){return <nav className="mobile-nav">{[["home","Discover"],["library","Library"],["community","Community"],["profile","Profile"]].map(([id,label])=><button className={view===id?"active":""} key={id} onClick={()=>nav(id)}>{label}</button>)}</nav>}
