export type CatalogueBook = {
  id: string;
  title: string;
  author: string;
  genres: string[];
  moods: string[];
  description: string;
  readingMinutes: number;
  cover?: string;
  publicDomain: boolean;
  sourceUrl: string;
  buyUrl?: string;
  communityCount: number;
  rating: number;
  ratingsCount: number;
  bites?: string[];
};

const bite = (title: string, points: string[]) => [
  `${title} in one breath: ${points[0]}.`,
  `The invitation: ${points[1]}.`,
  `Notice the central tension: ${points[2]}.`,
  `A useful lens for this reading: ${points[3]}.`,
  `The emotional weather is ${points[4]}.`,
  `Ask yourself: ${points[5]}.`,
  `Why it lasts: ${points[6]}.`,
  `Pause here and put one idea into your own words.`,
  `Save the thought that feels most useful today.`,
  `Ready for more? Choose the legal reading route below.`,
];

export const catalogue: CatalogueBook[] = [
  { id:"frankenstein", title:"Frankenstein", author:"Mary Shelley", genres:["Classic","Gothic"], moods:["Reflective","Adventurous"], description:"A public-domain gothic classic about ambition, responsibility and belonging.", readingMinutes:55, cover:"https://www.gutenberg.org/cache/epub/84/pg84.cover.medium.jpg", publicDomain:true, sourceUrl:"https://www.gutenberg.org/ebooks/84", communityCount:482, rating:4.2, ratingsCount:8241, bites:bite("Frankenstein",["a maker confronts the cost of treating life as a project","it asks us to look beyond first impressions","creation without care becomes abandonment","read it as a story about responsibility rather than a monster story","stormy, lonely and searching","what do we owe what we bring into the world","it makes moral questions feel personal"]) },
  { id:"pride", title:"Pride and Prejudice", author:"Jane Austen", genres:["Classic","Romance"], moods:["Cozy","Hopeful"], description:"A public-domain social comedy of wit, first impressions and slow-burn love.", readingMinutes:50, cover:"https://www.gutenberg.org/cache/epub/1342/pg1342.cover.medium.jpg", publicDomain:true, sourceUrl:"https://www.gutenberg.org/ebooks/1342", communityCount:691, rating:4.5, ratingsCount:17921, bites:bite("Pride and Prejudice",["sharp conversation meets the risk of judging too quickly","it rewards patient attention to what people do, not just what they say","pride and prejudice both conceal vulnerability","look for shifts in perception","witty, bright and quietly tender","where might certainty be getting in the way of curiosity","its humour still exposes human habits with precision"]) },
  { id:"jane-eyre", title:"Jane Eyre", author:"Charlotte Brontë", genres:["Classic","Coming of age"], moods:["Reflective","Hopeful"], description:"A public-domain novel of independence, courage and finding one’s own voice.", readingMinutes:65, cover:"https://www.gutenberg.org/cache/epub/1260/pg1260.cover.medium.jpg", publicDomain:true, sourceUrl:"https://www.gutenberg.org/ebooks/1260", communityCount:355, rating:4.3, ratingsCount:12108, bites:bite("Jane Eyre",["a young woman insists that dignity and belonging can coexist","it follows a voice becoming more certain of its own worth","love is tested against self-respect","notice how choices reveal values","intense, resilient and intimate","what boundary would help you remain yourself","its inner voice feels strikingly modern"]) },
  { id:"alice", title:"Alice’s Adventures in Wonderland", author:"Lewis Carroll", genres:["Classic","Fantasy"], moods:["Adventurous","Cozy"], description:"A public-domain, playful tumble through a world of curious logic.", readingMinutes:35, cover:"https://www.gutenberg.org/cache/epub/11/pg11.cover.medium.jpg", publicDomain:true, sourceUrl:"https://www.gutenberg.org/ebooks/11", communityCount:274, rating:4.0, ratingsCount:9830, bites:bite("Alice’s Adventures in Wonderland",["a curious child encounters a world that refuses ordinary rules","it invites playful attention rather than tidy answers","logic keeps changing under Alice’s feet","let confusion become part of the fun","whimsical, strange and light","what changes when you stop needing everything to make sense","its imagination keeps rewarding readers of every age"]) },
  { id:"secret-garden", title:"The Secret Garden", author:"Frances Hodgson Burnett", genres:["Classic","Feel-good"], moods:["Hopeful","Cozy"], description:"A public-domain story of friendship, fresh air and renewal.", readingMinutes:45, cover:"https://www.gutenberg.org/cache/epub/17396/pg17396.cover.medium.jpg", publicDomain:true, sourceUrl:"https://www.gutenberg.org/ebooks/17396", communityCount:519, rating:4.2, ratingsCount:7122, bites:bite("The Secret Garden",["a neglected place becomes a small practice of hope","it shows how attention and friendship can restore energy","isolation softens when care is shared","watch the garden as a mirror for inner change","gentle, restorative and sunlit","what small part of your life needs patient tending","its optimism never needs to shout"]) },
  { id:"walden", title:"Walden", author:"Henry David Thoreau", genres:["Classic","Philosophy"], moods:["Focused","Reflective"], description:"A public-domain meditation on simplicity, attention and deliberate living.", readingMinutes:40, cover:"https://www.gutenberg.org/cache/epub/205/pg205.cover.medium.jpg", publicDomain:true, sourceUrl:"https://www.gutenberg.org/ebooks/205", communityCount:198, rating:4.0, ratingsCount:5530, bites:bite("Walden",["a writer experiments with living more deliberately","it questions which wants are truly necessary","simplicity can create room for attention","take it as an invitation, not a rulebook","quiet, observant and challenging","what could you remove to make room for what matters","it keeps turning daily life into a philosophical question"]) },
  { id:"little-women", title:"Little Women", author:"Louisa May Alcott", genres:["Classic","Coming of age"], moods:["Cozy","Hopeful"], description:"A public-domain family story about ambition, affection and becoming oneself.", readingMinutes:55, cover:"https://www.gutenberg.org/cache/epub/514/pg514.cover.medium.jpg", publicDomain:true, sourceUrl:"https://www.gutenberg.org/ebooks/514", communityCount:641, rating:4.4, ratingsCount:13806, bites:bite("Little Women",["four sisters learn how affection and ambition can sit in the same home","it makes everyday choices emotionally meaningful","each character carries a different idea of a good life","notice the kindness inside ordinary scenes","warm, lively and honest","whose version of success feels closest to yours","it gives domestic life real moral weight"]) },
  { id:"dracula", title:"Dracula", author:"Bram Stoker", genres:["Classic","Gothic"], moods:["Adventurous","Focused"], description:"A public-domain gothic thriller told through letters, journals and reports.", readingMinutes:60, cover:"https://www.gutenberg.org/cache/epub/345/pg345.cover.medium.jpg", publicDomain:true, sourceUrl:"https://www.gutenberg.org/ebooks/345", communityCount:387, rating:4.1, ratingsCount:10423, bites:bite("Dracula",["a group of ordinary people piece together an extraordinary threat","it turns documents and voices into suspense","knowledge becomes a shared defence","notice how trust is built through evidence","tense, atmospheric and urgent","what helps a group act when the facts are incomplete","its format feels surprisingly modern"]) },
  { id:"sherlock-holmes", title:"The Adventures of Sherlock Holmes", author:"Arthur Conan Doyle", genres:["Classic","Mystery"], moods:["Focused","Adventurous"], description:"A public-domain collection of sharp, satisfying mysteries starring the world’s best-known consulting detective.", readingMinutes:45, cover:"https://www.gutenberg.org/cache/epub/1661/pg1661.cover.medium.jpg", publicDomain:true, sourceUrl:"https://www.gutenberg.org/ebooks/1661", communityCount:1042, rating:4.5, ratingsCount:22104, bites:bite("The Adventures of Sherlock Holmes",["a consulting detective solves problems by noticing what others miss","it makes reasoning feel like an entertaining game","each case asks which detail is hiding in plain sight","read for the chain of observation rather than the answer alone","clever, brisk and satisfying","what small detail would you usually overlook","the stories remain an ideal short reading session"]) },
  { id:"atomic-habits", title:"Atomic Habits", author:"James Clear", genres:["Non-fiction","Self growth"], moods:["Focused","Hopeful"], description:"A modern practical guide to making small actions easier to repeat.", readingMinutes:40, cover:"https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg", publicDomain:false, sourceUrl:"https://jamesclear.com/atomic-habits", buyUrl:"https://www.amazon.in/s?k=Atomic+Habits+James+Clear", communityCount:812, rating:4.6, ratingsCount:26410, bites:bite("Atomic Habits",["small repeatable choices can shape a larger direction","it is useful when motivation feels unreliable","the environment often decides more than willpower","look for one friction point you can reduce","practical, steady and encouraging","what tiny action could make tomorrow easier","it turns self-improvement into a system design problem"]) },
  { id:"kite-runner", title:"The Kite Runner", author:"Khaled Hosseini", genres:["Literary fiction","Contemporary"], moods:["Reflective","Hopeful"], description:"A modern novel about friendship, guilt, family and redemption.", readingMinutes:60, cover:"https://covers.openlibrary.org/b/isbn/9781594631931-L.jpg", publicDomain:false, sourceUrl:"https://www.khaledhosseini.com/", buyUrl:"https://www.amazon.in/s?k=The+Kite+Runner+Khaled+Hosseini", communityCount:733, rating:4.5, ratingsCount:21551, bites:bite("The Kite Runner",["a friendship is tested by loyalty, memory and the wish to make things right","it asks how people carry choices across time","redemption begins with facing what hurts","read slowly around its emotional turning points","tender, painful and ultimately searching","what does a sincere repair require","it gives moral questions a human face"]) },
  { id:"alchemist", title:"The Alchemist", author:"Paulo Coelho", genres:["Fiction","Fable"], moods:["Hopeful","Adventurous"], description:"A modern fable about purpose, risk and following a personal calling.", readingMinutes:35, cover:"https://covers.openlibrary.org/b/isbn/9780062315007-L.jpg", publicDomain:false, sourceUrl:"https://www.harpercollins.com/products/the-alchemist-paulo-coelho", buyUrl:"https://www.amazon.in/s?k=The+Alchemist+Paulo+Coelho", communityCount:945, rating:4.1, ratingsCount:29830, bites:bite("The Alchemist",["a young traveller follows a feeling that his life can become larger","it works best as a reflective fable, not a literal map","risk and attention move together","notice the moments where the journey changes the traveller","hopeful, spare and symbolic","what pursuit have you postponed because it feels uncertain","it offers a clear invitation to act"]) }
];

export const moods = ["Cozy","Focused","Hopeful","Reflective","Adventurous","Bright","Gloomy"] as const;
export type Mood = typeof moods[number];

export function fallbackRecommendations(mood: string, genres: string[] = []) {
  const moodMatches: Record<string, string[]> = { Bright:["Hopeful","Adventurous"], Gloomy:["Reflective","Focused"] };
  const accepted = moodMatches[mood] || [mood];
  const matched = catalogue.filter((book) => accepted.some((item) => book.moods.includes(item)) || book.genres.some((genre) => genres.includes(genre)));
  return (matched.length >= 3 ? matched : catalogue).slice(0, 3).map((book, index) => ({
    bookId: book.id,
    reason: index === 0 ? `This is the strongest fit for a ${mood.toLowerCase()} reading moment.` : `Its tone and reading commitment make it an easy next step for today.`
  }));
}
