"use client";
import { useEffect, useState } from "react";

type Book = { id:string; title:string; author:string; cover?:string; url:string; paid?:boolean; note?:string };
const books: Book[] = [
  {id:"84",title:"Frankenstein",author:"Mary Shelley",cover:"https://www.gutenberg.org/cache/epub/84/pg84.cover.medium.jpg",url:"https://www.gutenberg.org/ebooks/84"},
  {id:"1342",title:"Pride and Prejudice",author:"Jane Austen",cover:"https://www.gutenberg.org/cache/epub/1342/pg1342.cover.medium.jpg",url:"https://www.gutenberg.org/ebooks/1342"},
  {id:"1260",title:"Jane Eyre",author:"Charlotte Brontë",cover:"https://www.gutenberg.org/cache/epub/1260/pg1260.cover.medium.jpg",url:"https://www.gutenberg.org/ebooks/1260"},
  {id:"11",title:"Alice’s Adventures in Wonderland",author:"Lewis Carroll",cover:"https://www.gutenberg.org/cache/epub/11/pg11.cover.medium.jpg",url:"https://www.gutenberg.org/ebooks/11"},
  {id:"2701",title:"Moby-Dick",author:"Herman Melville",cover:"https://www.gutenberg.org/cache/epub/2701/pg2701.cover.medium.jpg",url:"https://www.gutenberg.org/ebooks/2701"},
  {id:"atomic",title:"Atomic Habits",author:"James Clear",url:"https://www.amazon.in/s?k=Atomic+Habits+James+Clear",paid:true,note:"Copyrighted book. Book Bites are original learning prompts; use the retailer link for the full book."},
  {id:"kite",title:"The Kite Runner",author:"Khaled Hosseini",url:"https://www.amazon.in/s?k=The+Kite+Runner+Khaled+Hosseini",paid:true,note:"Copyrighted book. Book Bites are an original orientation, not a substitute for the text."},
  {id:"alchemist",title:"The Alchemist",author:"Paulo Coelho",url:"https://www.amazon.in/s?k=The+Alchemist+Paulo+Coelho",paid:true,note:"Copyrighted book. Open a retailer to purchase or borrow the full edition."}
];
const moods={Cozy:"Soft edges, warm stories, one unrushed page.",Focused:"Clear space for one meaningful reading session.",Hopeful:"Light, forward-looking choices for today.",Reflective:"A quieter dashboard for ideas worth sitting with.",Adventurous:"Bigger worlds, sharper questions, more wonder."} as const;
const bites=["The premise, in one clear sentence.","The central question worth carrying into your day.","A character, idea, or tension to notice.","What changes when the story begins to move.","A practical lens: where this meets real life.","A moment to pause before judging the outcome.","The conflict beneath the surface.","One theme readers often return to.","A reflection prompt for your own notebook.","Ready for the full experience? Choose a legal reading route."];

function Poster({book,onOpen}:{book:Book;onOpen:()=>void}){return <button className="cover-button cover" onClick={onOpen} aria-label={`Open Book Bites for ${book.title}`}>{book.cover?<img src={book.cover} alt={`${book.title} cover`} onError={e=>e.currentTarget.style.display="none"}/>:<div className="cover-fallback">{book.title}</div>}<span>Read Book Bites</span></button>}

export default function Explore(){
 const [tab,setTab]=useState("Today"); const [dark,setDark]=useState(false); const [mood,setMood]=useState<keyof typeof moods>("Hopeful");
 const [library,setLibrary]=useState<Book[]>(books.slice(0,2)); const [results,setResults]=useState<Book[]>(books); const [query,setQuery]=useState("");
 const [reader,setReader]=useState<Book|null>(null); const [card,setCard]=useState(0); const [font,setFont]=useState(24); const [space,setSpace]=useState(1.75); const [theme,setTheme]=useState("paper");
 const [signedIn,setSignedIn]=useState(false); const [name,setName]=useState(""); const [authOpen,setAuthOpen]=useState(false); const [authMode,setAuthMode]=useState("Sign in");
 const [status,setStatus]=useState(""); const [joined,setJoined]=useState(false); const [vote,setVote]=useState(""); const [question,setQuestion]=useState(""); const [reply,setReply]=useState("Ask for a reading plan, a mood match, or a spoiler-free nudge."); const [source,setSource]=useState("ready");
 useEffect(()=>{const saved=localStorage.getItem("bt-library"),profile=localStorage.getItem("bt-profile");if(saved)try{setLibrary(JSON.parse(saved))}catch{}if(profile){setName(profile);setSignedIn(true)}},[]);
 useEffect(()=>localStorage.setItem("bt-library",JSON.stringify(library)),[library]);
 const openReader=(book:Book)=>{setReader(book);setCard(0);window.scrollTo({top:0,behavior:"smooth"})};
 const add=(book:Book)=>{setLibrary(x=>x.some(y=>y.id===book.id)?x:[book,...x]);setStatus(`${book.title} is in your library.`)};
 const signIn=()=>{const safe=name.trim()||"Reader";localStorage.setItem("bt-profile",safe);setName(safe);setSignedIn(true);setAuthOpen(false);setStatus(`Welcome, ${safe}. Your library is saved in this browser.`)};
 const signOut=()=>{localStorage.removeItem("bt-profile");setSignedIn(false);setName("");setStatus("You have been signed out on this browser.")};
 const search=async()=>{const q=query.trim();if(!q){setResults(books);return}const local=books.filter(b=>`${b.title} ${b.author}`.toLowerCase().includes(q.toLowerCase()));if(local.length){setResults(local);return}try{const r=await fetch(`/api/catalog?q=${encodeURIComponent(q)}`),d=await r.json();setResults(d.books?.length?d.books:[{id:"search",title:`Search Project Gutenberg for “${q}”`,author:"Official free-book catalogue",url:`https://www.gutenberg.org/ebooks/search/?query=${encodeURIComponent(q)}`,note:"Open the official catalogue for matching public-domain eBooks."}])}catch{setResults([{id:"search",title:`Search Project Gutenberg for “${q}”`,author:"Official free-book catalogue",url:`https://www.gutenberg.org/ebooks/search/?query=${encodeURIComponent(q)}`,note:"Open the official catalogue for matching public-domain eBooks."}])}};
 const ask=async()=>{if(!question.trim())return;setReply("Thinking…");try{const r=await fetch("/api/assistant",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:question,mood})}),d=await r.json();setReply(d.reply);setSource(d.source||"fallback")}catch{setReply("The companion needs a moment. Try again, or browse a Book Bite.");setSource("unavailable")}};
 if(reader)return <div className={dark?"dark":""}><main className="app"><header className="shell nav"><button className="brand" onClick={()=>setReader(null)}><span className="brand-mark">✦</span><span>Booktender <small>Your personal book bartender</small></span></button><button className="btn btn-soft btn-small" onClick={()=>setDark(!dark)}>Toggle dark mode</button></header><section className={`reader card ${theme}`}><div className="reader-top"><div><span className="eyebrow">Book Bites · {card+1} of 10</span><h1 className="serif">{reader.title}</h1><p>{reader.author}</p></div><button className="btn btn-soft btn-small" onClick={()=>setReader(null)}>← Back</button></div><div className="reader-controls"><label>Text <button onClick={()=>setFont(Math.max(18,font-2))}>A−</button><button onClick={()=>setFont(Math.min(34,font+2))}>A+</button></label><label>Spacing <button onClick={()=>setSpace(Math.max(1.35,space-.15))}>Tight</button><button onClick={()=>setSpace(Math.min(2.3,space+.15))}>Airy</button></label><label>Theme <button onClick={()=>setTheme("paper")}>Paper</button><button onClick={()=>setTheme("sepia")}>Sepia</button><button onClick={()=>setTheme("night")}>Night</button></label></div><p className="reader-copy" style={{fontSize:font,lineHeight:space}}>{bites[card]}{"\n\n"}This is an original Booktender flashcard designed to help you decide whether this book is for you. It does not reproduce the book or a third-party summary.</p><div className="reader-actions"><button className="btn btn-soft" disabled={card===0} onClick={()=>setCard(card-1)}>Previous</button>{card<9?<button className="btn btn-primary" onClick={()=>setCard(card+1)}>Next card</button>:<button className="btn btn-primary" onClick={()=>window.open(reader.url,"_blank","noopener,noreferrer")}>{reader.paid?"Find the full book":"Read the full book free"}</button>}</div>{card===9&&<p className="legal-note">{reader.paid?"This title is copyrighted. Booktender does not provide its full text.":"This title links to a legal public-domain source."}</p>}</section></main></div>;
 const nav=["Today","Find books","Community","Admin"];
 return <div className={dark?"dark":""}><main className="app"><header className="shell nav"><button className="brand" onClick={()=>setTab("Today")}><span className="brand-mark">✦</span><span>Booktender <small>Your personal book bartender</small></span></button><nav className="nav-links">{nav.map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</nav><div className="nav-actions">{signedIn?<><span className="pill">Hi, {name}</span><button className="btn btn-soft btn-small" onClick={signOut}>Log out</button></>:<button className="btn btn-soft btn-small" onClick={()=>{setAuthMode("Sign in");setAuthOpen(true)}}>Sign in / Sign up</button>}<button className="icon" onClick={()=>setDark(!dark)} aria-label="Toggle dark mode">{dark?"☀":"◐"}</button></div></header>
 {authOpen&&<section className="auth-overlay"><article className="auth-card card"><button className="auth-close" onClick={()=>setAuthOpen(false)}>×</button><span className="eyebrow">Your Booktender account</span><h2 className="serif">{authMode}</h2><p>Use any name for this browser demo. Real cross-device accounts need Supabase authentication next.</p><input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name" autoFocus/><button className="btn btn-primary" onClick={signIn}>{authMode}</button><button className="text-button" onClick={()=>setAuthMode(authMode==="Sign in"?"Sign up":"Sign in")}>{authMode==="Sign in"?"New here? Sign up":"Already have an account? Sign in"}</button></article></section>}
 {tab==="Today"&&<section className="shell"><article className="mood-panel card"><span className="eyebrow">Your reading personality today</span><h1 className="serif mood-title">Feeling {mood.toLowerCase()}.</h1><p>{moods[mood]}</p><div className="mood-grid">{Object.keys(moods).map(x=><button key={x} className={"mood-chip "+(mood===x?"active":"")} onClick={()=>setMood(x as keyof typeof moods)}>{x}</button>)}</div></article><article className="spotlight card"><span className="eyebrow">Literary spotlight</span><blockquote>“Tomorrow is always fresh, with no mistakes in it yet.”</blockquote><cite>L. M. Montgomery · Anne of Green Gables</cite></article><section className="section"><div className="section-head"><div><span className="eyebrow">Your own library</span><h2>Saved for your next good hour</h2></div><button className="btn btn-primary" onClick={()=>setTab("Find books")}>Find books</button></div><div className="catalogue-grid">{library.slice(0,5).map(book=><article className="catalogue-card card" key={book.id}><Poster book={book} onOpen={()=>openReader(book)}/><h3>{book.title}</h3><p>{book.author}</p><button className="btn btn-soft btn-small" onClick={()=>openReader(book)}>Open Book Bites</button></article>)}</div></section></section>}
 {tab==="Find books"&&<section className="shell section"><span className="eyebrow">Classics, famous books, and legal routes</span><h1 className="serif find-title">Find your next book.</h1><p className="intro">Every poster opens Book Bites first: ten original flashcards with reader controls. Public-domain books then open free legal sources; paid books go to a purchase search.</p><div className="catalogue-controls"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&search()} placeholder="Search title, author, theme or genre…"/><button className="btn btn-primary" onClick={search}>Search catalogue</button></div><div className="catalogue-grid">{results.map(book=><article className="catalogue-card card" key={book.id}><Poster book={book} onOpen={()=>openReader(book)}/><h3>{book.title}</h3><p>{book.author}</p>{book.note&&<p className="book-note">{book.note}</p>}<div className="book-actions"><button className="btn btn-primary btn-small" onClick={()=>add(book)}>+ My library</button><button className="btn btn-soft btn-small" onClick={()=>openReader(book)}>Book Bites</button></div></article>)}</div><p className="status">{status}</p><article className="chatbox card"><span className="eyebrow">Ask Booktender</span><h2 className="serif">A quiet reading companion</h2><div className="chat-reply">{reply}</div><div className="input-row"><input className="chat-input" value={question} onChange={e=>setQuestion(e.target.value)} placeholder="I have 20 minutes and want something hopeful…"/><button className="btn btn-primary" onClick={ask}>Ask</button></div><small>Response source: {source}. It never provides pirated full books.</small></article></section>}
 {tab==="Community"&&<section className="shell section"><article className="community-hero card"><span className="eyebrow">The Sunday Shelf</span><h1>A book community without the noise.</h1><p>Theme rooms, buddy reads, a shared challenge and one thoughtful event at a time.</p></article><div className="community-ideas"><article className="idea card"><span className="eyebrow">Mood room</span><h3>Gentle reads for tired weeks</h3><p>128 readers · short sessions · no performance.</p><button className="btn btn-sage btn-small" onClick={()=>setStatus("Mood room saved to your community list.")}>Join room</button></article><article className="idea card"><span className="eyebrow">Buddy read</span><h3>Walden in seven days</h3><p>One reflection prompt each day.</p><button className="btn btn-sage btn-small" onClick={()=>setStatus("Buddy read seat saved.")}>Save my seat</button></article><article className="idea card"><span className="eyebrow">Community vote</span><h3>Our next discussion</h3><p>{vote?`You voted for ${vote}.`:"Choose the next shared book."}</p>{["Kindred","Little Women","A new discovery"].map(x=><button className="btn btn-soft btn-small" key={x} onClick={()=>setVote(x)}>{x}</button>)}</article></div><article className="comment-box card"><span className="eyebrow">Upcoming gathering</span><h2 className="serif">The Secret Garden · Saturday 6:30 pm IST</h2><p>{joined?"You’re on the guest list. We’ll save your place in this demo community.":"Bring one line that stayed with you. Spoiler-light, first-timers welcome."}</p><button className="btn btn-primary" onClick={()=>setJoined(true)}>{joined?"You’re joining ✓":"I’m joining"}</button><p className="status">{status}</p></article></section>}
 {tab==="Admin"&&<section className="shell section"><span className="eyebrow">Safe public preview</span><h1 className="serif">Admin without unsafe access.</h1><div className="admin-note">This is a read-only demo. Proper admin roles, accounts, saved libraries and community data are the Supabase build step—not something a browser-only demo can pretend to have.</div></section>}
 </main></div>;
}
