"use client";

import { useEffect, useMemo, useState } from "react";
import { catalogue, fallbackRecommendations, moods, type CatalogueBook, type Mood } from "../../lib/catalogue";
import { supabase } from "../../lib/supabase";

type Shelf = "queue" | "reading" | "read";
type LibraryItem = { book: CatalogueBook; shelf: Shelf; progress: number; page: number };
type Recommendation = { book: CatalogueBook; reason: string };
type Profile = { name: string; genres: string[]; readIds: string[] };
const quoteSlides = [
  { quote:"Tomorrow is always fresh, with no mistakes in it yet.", author:"L. M. Montgomery", source:"Anne of Green Gables", tone:"lavender" },
  { quote:"The moment you doubt whether you can fly, you cease forever to be able to do it.", author:"J. M. Barrie", source:"Peter Pan", tone:"blue" },
  { quote:"There is no charm equal to tenderness of heart.", author:"Jane Austen", source:"Emma", tone:"peach" }
];
const genres = ["Classic","Fantasy","Romance","Literary fiction","Non-fiction","Self growth","Philosophy","Mystery"];

function Logo(){return <div className="logo"><span className="logo-mark"><i></i><b>✦</b></span><span><strong><em>B</em>ooktender</strong><small>Your personal book bartender</small></span></div>}
function Cover({book, onClick}:{book:CatalogueBook;onClick:()=>void}){return <button className="book-cover" onClick={onClick} aria-label={`Open Book Bites for ${book.title}`}>{book.cover?<img src={book.cover} alt={`${book.title} cover`} />:<span>{book.title}</span>}</button>}
function toastText(setter:(value:string)=>void,text:string){setter(text);window.setTimeout(()=>setter(""),3500)}

export default function Booktender(){
  const [screen,setScreen]=useState<"auth"|"onboarding"|"app"|"reader">("auth");
  const [dark,setDark]=useState(false); const [tab,setTab]=useState("Discover"); const [authMode,setAuthMode]=useState<"signin"|"signup">("signin");
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [profile,setProfile]=useState<Profile>({name:"",genres:[],readIds:[]});
  const [mood,setMood]=useState<Mood>("Hopeful"); const [request,setRequest]=useState("I want something hopeful, short and easy to read."); const [recs,setRecs]=useState<Recommendation[]>([]); const [recSource,setRecSource]=useState("ready");
  const [library,setLibrary]=useState<LibraryItem[]>([]); const [reader,setReader]=useState<CatalogueBook|null>(null); const [cards,setCards]=useState<string[]>([]); const [card,setCard]=useState(0); const [font,setFont]=useState(23); const [spacing,setSpacing]=useState(1.8); const [readerTheme,setReaderTheme]=useState("paper");
  const [spot,setSpot]=useState(0); const [quote,setQuote]=useState(""); const [streak,setStreak]=useState(3); const [completed,setCompleted]=useState(2); const [minutes,setMinutes]=useState(35); const [communityNote,setCommunityNote]=useState(""); const [comments,setComments]=useState(["The Secret Garden is my comfort re-read.","I saved Pride and Prejudice after this week's recommendation."]);
  const [status,setStatus]=useState(""); const [busy,setBusy]=useState(false);

  useEffect(()=>{const saved=localStorage.getItem("booktender-profile"), shelf=localStorage.getItem("booktender-library"), stats=localStorage.getItem("booktender-stats"); if(saved){try{setProfile(JSON.parse(saved));setScreen("app")}catch{}} if(shelf)try{setLibrary(JSON.parse(shelf))}catch{} if(stats)try{const s=JSON.parse(stats);setStreak(s.streak||3);setCompleted(s.completed||2);setMinutes(s.minutes||35)}catch{} const timer=window.setInterval(()=>setSpot(x=>(x+1)%quoteSlides.length),7000); return()=>window.clearInterval(timer)},[]);
  useEffect(()=>{if(screen==="app")localStorage.setItem("booktender-profile",JSON.stringify(profile));localStorage.setItem("booktender-library",JSON.stringify(library));localStorage.setItem("booktender-stats",JSON.stringify({streak,completed,minutes}))},[profile,library,streak,completed,minutes,screen]);
  useEffect(()=>{if(!supabase)return; supabase.auth.getSession().then(({data})=>{if(data.session?.user){setProfile(x=>({...x,name:data.session?.user.user_metadata.display_name||x.name||"Reader"}));setScreen("app")}})},[]);
  const current = useMemo(()=>quoteSlides[spot], [spot]);
  const libraryFor=(shelf:Shelf)=>library.filter(item=>item.shelf===shelf);
  const personality = mood==="Hopeful"?"The Sunlit Optimist":mood==="Cozy"?"The Gentle Recharger":mood==="Focused"?"The Intentional Reader":mood==="Reflective"?"The Quiet Explorer":"The Curious Wanderer";

  const auth=async()=>{if(!email.includes("@")||password.length<6){toastText(setStatus,"Use a valid email and a password of at least 6 characters.");return}if(!supabase){setProfile(x=>({...x,name:email.split("@")[0]}));setScreen("onboarding");toastText(setStatus,"Demo mode is active. Add Supabase to enable real accounts.");return}setBusy(true);const result=authMode==="signup"?await supabase.auth.signUp({email,password,options:{data:{display_name:email.split("@")[0]}}}):await supabase.auth.signInWithPassword({email,password});setBusy(false);if(result.error){toastText(setStatus,result.error.message);return}if(authMode==="signup"&&!result.data.session){toastText(setStatus,"Check your email to confirm the account, then sign in.");return}setProfile(x=>({...x,name:email.split("@")[0]}));setScreen("onboarding")};
  const demo=()=>{setProfile({name:"Jamie",genres:["Classic","Fantasy"],readIds:["frankenstein","pride","alice"]});setScreen("app");setRecs(fallbackRecommendations("Hopeful",["Classic"]).map(item=>({book:catalogue.find(book=>book.id===item.bookId)!,reason:item.reason})))};
  const finishOnboarding=async()=>{if(!profile.name.trim()||profile.genres.length===0||profile.readIds.length<3){toastText(setStatus,"Add your name, at least one genre and three books you have read.");return}if(supabase){const {data}=await supabase.auth.getUser();if(data.user)await supabase.from("profiles").upsert({id:data.user.id,display_name:profile.name,favourite_genres:profile.genres})}setScreen("app");setTab("Discover");toastText(setStatus,"Your shelf is ready. Tell Booktender what you feel like reading.")};
  const recommend=async()=>{setBusy(true);try{const response=await fetch("/api/recommendations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mood,genres:profile.genres,prompt:request,readIds:profile.readIds})});const data=await response.json();setRecs(data.recommendations);setRecSource(data.source)}catch{setRecs(fallbackRecommendations(mood,profile.genres).map(item=>({book:catalogue.find(book=>book.id===item.bookId)!,reason:item.reason})));setRecSource("Booktender fallback")}setBusy(false)};
  const saveBook=async(book:CatalogueBook,shelf:Shelf="queue")=>{setLibrary(items=>{const old=items.find(item=>item.book.id===book.id);return old?items.map(item=>item.book.id===book.id?{...item,shelf}:item):[{book,shelf,progress:0,page:1},...items]});if(supabase){const {data}=await supabase.auth.getUser();if(data.user)await supabase.from("user_books").upsert({user_id:data.user.id,book_id:book.id,status:shelf})}toastText(setStatus,`${book.title} is on your ${shelf==="queue"?"reading queue":shelf} shelf.`)};
  const openReader=async(book:CatalogueBook)=>{setReader(book);setCards([]);setCard(0);setScreen("reader");try{const response=await fetch("/api/book-bites",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({bookId:book.id})});const data=await response.json();setCards(data.cards||[])}catch{setCards([])}};
  const completeSession=()=>{if(!reader)return;setLibrary(items=>items.map(item=>item.book.id===reader.id?{...item,shelf:card>=8?"read":"reading",progress:Math.max(item.progress,Math.round(((card+1)/10)*100)),page:card+1}:item));setStreak(x=>x+1);setMinutes(x=>x+12);if(card>=8)setCompleted(x=>x+1);toastText(setStatus,"Reading session saved. Your streak has grown.")};
  const signOut=async()=>{if(supabase)await supabase.auth.signOut();localStorage.removeItem("booktender-profile");setScreen("auth");setTab("Discover");setProfile({name:"",genres:[],readIds:[]})};

  if(screen==="reader"&&reader)return <div className={dark?"dark":""}><main className="reader-app"><header className="reader-nav"><button onClick={()=>setScreen("app")}>← Back to Booktender</button><Logo/><button onClick={()=>setDark(!dark)}>{dark?"Light mode":"Dark mode"}</button></header><article className={`reader-surface ${readerTheme}`}><div className="reader-heading"><div><span className="eyebrow">Book Bites · {card+1} of 10 · {cards.length?"AI-supported":"Loading"}</span><h1>{reader.title}</h1><p>{reader.author}</p></div><button className="save-link" onClick={()=>toastText(setStatus,"Page bookmarked.")}>Bookmark</button></div><div className="reader-tools"><span>Text <button onClick={()=>setFont(x=>Math.max(18,x-2))}>A−</button><button onClick={()=>setFont(x=>Math.min(32,x+2))}>A+</button></span><span>Spacing <button onClick={()=>setSpacing(1.45)}>Tight</button><button onClick={()=>setSpacing(2.05)}>Airy</button></span><span>Theme <button onClick={()=>setReaderTheme("paper")}>Paper</button><button onClick={()=>setReaderTheme("sepia")}>Sepia</button><button onClick={()=>setReaderTheme("night")}>Night</button></span></div><p className="bite-copy" style={{fontSize:font,lineHeight:spacing}}>{cards[card]||"Preparing a calm, spoiler-free Book Bite for you…"}</p><div className="reader-progress"><span style={{width:`${((card+1)/10)*100}%`}}></span></div><div className="reader-footer"><button className="ghost" disabled={card===0} onClick={()=>setCard(x=>x-1)}>Previous</button>{card<9?<button className="primary" onClick={()=>{setCard(x=>x+1);completeSession()}}>Next page</button>:<button className="primary" onClick={()=>window.open(reader.publicDomain?reader.sourceUrl:(reader.buyUrl||reader.sourceUrl),"_blank","noopener,noreferrer")}>{reader.publicDomain?"Read full book free":"Find the full book"}</button>}</div><button className="quote-save" onClick={()=>{setQuote(cards[card]||"");toastText(setStatus,"Book Bite saved to your quotes.")}}>Save this thought</button>{status&&<p className="status">{status}</p>}</article></main></div>;

  if(screen==="auth")return <div className={dark?"dark":""}><main className="auth-page"><header className="auth-top"><Logo/><div><button className="tiny" onClick={()=>setDark(!dark)}>{dark?"☀":"◐"}</button><button className="language">English⌄</button></div></header><div className="auth-grid"><section className="auth-story"><div className="floating one">The Midnight Library</div><div className="floating two">Legends & Lattes</div><div className="floating three">Seven Husbands</div><span className="concierge">Your AI book concierge</span><h1>Books that match your <em>mood.</em></h1><p>Tell Booktender how you feel. Get exactly three thoughtful books — with a reason why and a place to begin.</p><ul><li>Mood-first, not another taste quiz</li><li>Exactly 3 picks, each with a “why”</li><li>A warm companion, not a cold algorithm</li></ul><p className="handwritten">A reader lives a thousand lives before they die.</p></section><section className="auth-card"><Logo/><p>Sign in to your reading journey</p><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email" type="email"/><input value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" type="password"/><button className="primary wide" onClick={auth} disabled={busy}>{busy?"One moment…":authMode==="signin"?"Sign in":"Create account"}</button><div className="or">or explore as</div><button className="demo" onClick={demo}><b>📚 Demo reader</b><small>Explore the full product</small></button><button className="text-action" onClick={()=>setAuthMode(x=>x==="signin"?"signup":"signin")}>{authMode==="signin"?"New here? Create an account":"Already have an account? Sign in"}</button>{status&&<p className="status">{status}</p>}</section></div></main></div>;

  if(screen==="onboarding")return <div className={dark?"dark":""}><main className="onboarding"><header className="simple-head"><Logo/><button className="tiny" onClick={()=>setDark(!dark)}>Toggle dark</button></header><section className="onboard-card"><span className="eyebrow">A short welcome ritual</span><h1>Let’s make your shelf feel like yours.</h1><label>Your name<input value={profile.name} onChange={e=>setProfile(x=>({...x,name:e.target.value}))} placeholder="What should we call you?"/></label><div><b>Favourite genres</b><div className="chips">{genres.map(g=><button key={g} className={profile.genres.includes(g)?"chip selected":"chip"} onClick={()=>setProfile(x=>({...x,genres:x.genres.includes(g)?x.genres.filter(v=>v!==g):[...x.genres,g]}))}>{g}</button>)}</div></div><div><b>Three books you have already read</b><div className="read-grid">{catalogue.slice(0,6).map(book=><button className={profile.readIds.includes(book.id)?"read-choice selected":"read-choice"} key={book.id} onClick={()=>setProfile(x=>({...x,readIds:x.readIds.includes(book.id)?x.readIds.filter(v=>v!==book.id):x.readIds.length<3?[...x.readIds,book.id]:x.readIds}))}>{book.title}</button>)}</div><small>Select exactly three to help Booktender avoid repeats.</small></div><button className="primary" onClick={finishOnboarding}>Set my reading table →</button>{status&&<p className="status">{status}</p>}</section></main></div>;

  const nav=["Discover","My Library","Community","Profile","Admin"];
  return <div className={dark?"dark":""}><main className="app-shell"><header className="app-head"><Logo/><nav>{nav.map(item=><button key={item} className={tab===item?"active":""} onClick={()=>setTab(item)}>{item}</button>)}</nav><div className="head-actions"><button className="ask" onClick={()=>setTab("Discover")}>Ask Booktender</button><button className="tiny" onClick={()=>setDark(!dark)}>{dark?"☀":"◐"}</button><button className="avatar" onClick={()=>setTab("Profile")}>{profile.name.slice(0,1)||"R"}</button></div></header>
  {tab==="Discover"&&<section className="page"><div className="discover-hero"><span className="eyebrow">Your reading moment</span><h1>What would you like to feel?</h1><p>Booktender pours exactly three real books with a reason why each belongs in your day.</p><textarea value={request} onChange={e=>setRequest(e.target.value)} aria-label="Describe your reading mood"/><div className="mood-row">{moods.map(item=><button key={item} className={mood===item?"mood active":"mood"} onClick={()=>setMood(item)}>{item}</button>)}</div><button className="primary pour" onClick={recommend} disabled={busy}>{busy?"Finding your three…":"Find my 3 books ✦"}</button></div>{recs.length>0&&<><div className="pour-line"><span>Love that energy. Here’s what I’d pour you.</span><b>{mood} and personal</b></div><div className="recommend-grid">{recs.map(({book,reason})=><article className="recommend-card" key={book.id}><Cover book={book} onClick={()=>openReader(book)}/><div className="rec-body"><h2>{book.title}</h2><p>{book.author}</p><div className="reason">{reason}</div><small>{book.readingMinutes} mins · {book.communityCount} readers saved this</small><div className="card-actions"><button onClick={()=>openReader(book)}>Book Bites</button><button onClick={()=>saveBook(book)}>Save</button><button onClick={()=>window.open(book.publicDomain?book.sourceUrl:(book.buyUrl||book.sourceUrl),"_blank","noopener,noreferrer")}>{book.publicDomain?"Read free":"Buy"}</button></div></div></article>)}</div><div className="next-row"><button className="primary" onClick={recommend}>Pour 3 more ✦</button></div><section className="personality"><div><span className="eyebrow">Your reading personality</span><h2>{personality}</h2></div><button className="primary" onClick={()=>{setCommunityNote(`Shared my ${mood.toLowerCase()} picks`);setTab("Community")}}>Share my 3 picks →</button></section><button className="start-over" onClick={()=>{setRecs([]);setRequest("")}}>Start over with a new feeling</button></>}
  {!recs.length&&<><section className={`spotlight ${current.tone}`}><button onClick={()=>setSpot(x=>(x+quoteSlides.length-1)%quoteSlides.length)}>←</button><div><span className="eyebrow">Literary spotlight</span><blockquote>“{current.quote}”</blockquote><p>{current.author} · {current.source}</p></div><button onClick={()=>setSpot(x=>(x+1)%quoteSlides.length)}>→</button></section><section className="quick-grid"><article><span className="eyebrow">Continue reading</span><h2>{libraryFor("reading")[0]?.book.title||"Choose your first Book Bite"}</h2><p>{libraryFor("reading").length?"Your place is waiting.":"A small reading session counts."}</p><button className="ghost" onClick={()=>libraryFor("reading")[0]&&openReader(libraryFor("reading")[0].book)}>Resume</button></article><article><span className="eyebrow">Reading rhythm</span><h2>{streak} day streak</h2><p>Read gently. Consistency beats intensity.</p><div className="days">{["M","T","W","T","F","S","S"].map((day,index)=><span className={index<5?"done":""} key={index}>{day}</span>)}</div></article><article><span className="eyebrow">Community challenge</span><h2>Read 2,000 pages together</h2><p>1,462 pages this week</p><div className="bar"><i></i></div><button className="ghost" onClick={()=>setTab("Community")}>Join the shelf</button></article></section></>}</section>}
  {tab==="My Library"&&<section className="page"><span className="eyebrow">Your personal shelf</span><h1>Books you meant to remember.</h1><p className="lead">Move books between shelves, resume a Book Bite, and keep your reading momentum visible.</p>{(["reading","queue","read"] as Shelf[]).map(shelf=><section className="shelf" key={shelf}><div><h2>{shelf==="reading"?"Currently reading":shelf==="queue"?"Reading queue":"Finished"}</h2><span>{libraryFor(shelf).length} books</span></div><div className="shelf-books">{libraryFor(shelf).length?libraryFor(shelf).map(item=><article key={item.book.id}><Cover book={item.book} onClick={()=>openReader(item.book)}/><b>{item.book.title}</b><small>{item.progress}% complete</small><select value={item.shelf} onChange={e=>saveBook(item.book,e.target.value as Shelf)}><option value="queue">Queue</option><option value="reading">Reading</option><option value="read">Read</option></select></article>):<p className="empty">Nothing here yet. Discover your next three.</p>}</div></section>)}</section>}
  {tab==="Community"&&<section className="page"><section className="community-banner"><span className="eyebrow">The Sunday Shelf</span><h1>A book community without the noise.</h1><p>{communityNote||"Shared books, one thoughtful event and small conversations that help people keep reading."}</p></section><div className="community-grid"><article><span className="eyebrow">Upcoming gathering</span><h2>The Secret Garden</h2><p>Saturday · 6:30 pm IST · spoiler-light</p><button className="primary" onClick={()=>toastText(setStatus,"You’re on the guest list.")}>I’m joining</button></article><article><span className="eyebrow">Shared challenge</span><h2>Read 2,000 pages together</h2><div className="big-progress"><i></i></div><p>1,462 / 2,000 pages · 128 readers</p></article><article><span className="eyebrow">Popular on the shelf</span><h2>Pride and Prejudice</h2><p>Saved by 691 readers this month.</p><button className="ghost" onClick={()=>openReader(catalogue[1])}>Open Book Bites</button></article></div><section className="comments"><span className="eyebrow">Conversation</span>{comments.map((comment,index)=><p key={index}>✦ {comment}</p>)}<div><input value={communityNote} onChange={e=>setCommunityNote(e.target.value)} placeholder="Recommend a book to the group…"/><button className="primary" onClick={()=>{if(communityNote.trim()){setComments(x=>[communityNote,...x]);setCommunityNote("")}}}>Share</button></div></section>{status&&<p className="status">{status}</p>}</section>}
  {tab==="Profile"&&<section className="page"><span className="eyebrow">Your reading life</span><h1>Hello, {profile.name}.</h1><div className="stats"><article><b>{streak}</b><span>Current streak</span></article><article><b>{completed}</b><span>Books completed</span></article><article><b>{minutes}</b><span>Reading minutes</span></article><article><b>{quote?1:0}</b><span>Saved quotes</span></article></div><section className="profile-card"><h2>{personality}</h2><p>Your shelf leans toward {profile.genres.join(", ")||"the unexpected"}. Keep choosing the next small page.</p><button className="ghost" onClick={signOut}>Log out</button></section></section>}
  {tab==="Admin"&&<section className="page"><span className="eyebrow">Private team workspace</span><h1>Content administration</h1><p className="lead">The public deployment keeps admin data private. Once Supabase roles are configured, this screen is restricted to approved admins.</p><div className="admin-grid"><article><b>{catalogue.length}</b><span>Seeded verified books</span></article><article><b>10</b><span>Book Bites per title</span></article><article><b>1</b><span>Seeded community</span></article></div><div className="admin-note">Coming next: secure catalogue, event and challenge creation after the Supabase admin role is configured.</div></section>}
  </main>{status&&tab!=="Community"&&<div className="toast">{status}</div>}</div>;
}
