-- Booktender MVP schema. Apply through Supabase CLI or SQL Editor after review.
create extension if not exists "pgcrypto";

create type public.shelf_status as enum ('queue','reading','read');
create table public.profiles (id uuid primary key references auth.users on delete cascade, display_name text not null default 'Reader', favourite_genres text[] not null default '{}', role text not null default 'reader' check (role in ('reader','admin')), created_at timestamptz not null default now());
create table public.books (id text primary key, title text not null, author text not null, genres text[] not null default '{}', mood_tags text[] not null default '{}', description text not null, reading_minutes integer, public_domain boolean not null default false, content_type text not null default 'summary', created_at timestamptz not null default now());
create table public.user_books (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users on delete cascade, book_id text not null references public.books on delete cascade, status public.shelf_status not null default 'queue', progress_percentage integer not null default 0 check (progress_percentage between 0 and 100), current_page integer not null default 1, unique(user_id,book_id));
create table public.reading_content (id uuid primary key default gen_random_uuid(), book_id text not null references public.books on delete cascade, page_number integer not null, page_text text not null, source_note text not null, unique(book_id,page_number));
create table public.bookmarks (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users on delete cascade, book_id text not null references public.books on delete cascade, page_number integer not null, created_at timestamptz not null default now());
create table public.highlights (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users on delete cascade, book_id text not null references public.books on delete cascade, page_number integer not null, highlighted_text text not null, note text, created_at timestamptz not null default now());
create table public.saved_quotes (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users on delete cascade, book_id text references public.books on delete set null, quote_text text not null, created_at timestamptz not null default now());
create table public.reading_sessions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users on delete cascade, book_id text references public.books on delete set null, minutes_read integer not null default 0, session_date date not null default current_date, created_at timestamptz not null default now());
create table public.recommendations (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users on delete cascade, book_id text not null references public.books on delete cascade, reason text not null, batch integer not null, created_at timestamptz not null default now());
create table public.communities (id uuid primary key default gen_random_uuid(), name text not null, description text not null, current_book_id text references public.books, next_event_at timestamptz);
create table public.community_comments (id uuid primary key default gen_random_uuid(), community_id uuid not null references public.communities on delete cascade, user_id uuid references auth.users on delete set null, comment_text text not null, created_at timestamptz not null default now());

alter table public.profiles enable row level security; alter table public.books enable row level security; alter table public.user_books enable row level security; alter table public.reading_content enable row level security; alter table public.bookmarks enable row level security; alter table public.highlights enable row level security; alter table public.saved_quotes enable row level security; alter table public.reading_sessions enable row level security; alter table public.recommendations enable row level security; alter table public.communities enable row level security; alter table public.community_comments enable row level security;
create policy "public catalogue read" on public.books for select using (true); create policy "public content read" on public.reading_content for select using (true); create policy "public community read" on public.communities for select using (true); create policy "public comments read" on public.community_comments for select using (true);
create policy "own profile" on public.profiles for all using (auth.uid()=id) with check (auth.uid()=id); create policy "own library" on public.user_books for all using (auth.uid()=user_id) with check (auth.uid()=user_id); create policy "own bookmarks" on public.bookmarks for all using (auth.uid()=user_id) with check (auth.uid()=user_id); create policy "own highlights" on public.highlights for all using (auth.uid()=user_id) with check (auth.uid()=user_id); create policy "own quotes" on public.saved_quotes for all using (auth.uid()=user_id) with check (auth.uid()=user_id); create policy "own sessions" on public.reading_sessions for all using (auth.uid()=user_id) with check (auth.uid()=user_id); create policy "own recommendations" on public.recommendations for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "authenticated comments" on public.community_comments for insert to authenticated with check (auth.uid()=user_id);
